service_name: pythonagent_001
reporting:
  endpoint: http://localhost:9411/api/v2/spans1
  secure: true
data_capture:
  http_headers:
    request: true
    response: true
  http_body:
    request: true
    response: true
  rpc_metadata:
    request: true
    response: true
  rpc_body:
    request: true
    response: true
