#!/bin/bash
# This file is used as a runner for the original collector
# The name has to match the produced artifact exactly, since the associated artifact is what
# communicates with the lambda runtime api.
CONFIG_PATH=/opt/extensions/config/collector.yaml

# If we don't log & exit the collector will run until timeout with a log that says:
# "Processing config at path"
if [[ -z "${TPA_ENDPOINT}" ]]; then
  echo "Must set TPA_ENDPOINT environment variable"
  exit
fi
OPENTELEMETRY_COLLECTOR_CONFIG_FILE=${CONFIG_PATH} ./opt/extensions/exec/collector