on:
  push:
    branches: [main]
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**/*.md"
      - "LICENSE"

  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        python: ["3.7", "3.8", "3.9"]

    steps:
      - name: Run apt-get update
        run: sudo apt-get update

      - name: Install make
        run: sudo apt-get install make

      - name: install software-properties-common
        run: sudo apt install software-properties-common

      - name: Install Python versions
        run: |
          sudo add-apt-repository ppa:deadsnakes/ppa -y &&
          sudo apt-get install python${{ matrix.python }}

      - uses: actions/checkout@v2

      - name: Install pip
        run: sudo apt-get install python3-pip

      - name: Install tox
        run: pip install --user -r dev-requirements.txt

      - name: Run pylint on this branch to generate a report
        run: make lint

      - name: Install protobuf compiler
        run: |
          sudo apt-get install -y protobuf-compiler
          protoc --version
          pip uninstall protobuf python3-protobuf
          pip install --upgrade pip
          pip install --upgrade protobuf

      - name: Run tests
        run: PYTHON_VERSION=${{ matrix.python }} make test
