on:
  push:
    branches: [feature/develop, main]
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
  pull_request:
    branches: [feature/develop, main]
    paths-ignore:
      - "**/*.md"
      - "LICENSE"

  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-20.04

    steps:
      - name: Run apt-get update
        run: sudo apt-get update

      - name: Install make
        run: sudo apt-get install make

      - name: install software-properties-common
        run: sudo apt install software-properties-common

      - name: Install Python versions
        run: |
          sudo add-apt-repository ppa:deadsnakes/ppa -y &&
          sudo apt-get install python3.7 &&
          sudo apt-get install python3.8 &&
          sudo apt-get install python3.9

      - uses: actions/checkout@v2

      - name: Install pip
        run: sudo apt-get install python3-pip

      - name: Install tox
        run: pip install --user -r dev-requirements.txt

      - name: Run lint
        run: make lint

      - name: Run tests
        run: make test

      - name: Build package1
        run: python -m pip install --upgrade build

      - name: Build package2
        run: python3 -m build
#      - name: Push binary package to private package repo
#        uses: cpina/github-action-push-to-another-repository@master
#        env:
#          API_TOKEN_GITHUB:
#        with:
#          source-directory: dist
#          destination-repository-name: hypertrace-pythonagent
#          destination-github-username: rcbj
#          target-branch: main

#      - name: Create src package to copy to repo for installs
#        run: mkdir -p src_install/src
#
#      - name: copy files into src_install 1
#        run: cp -R src/hypertrace src/hypertrace.egg-info src_install/src
#
#      - name: copy files into src_install 2
#        run: cp LICENSE README.md pyproject.toml setup.py src_install
#
#      - name: Push src package to private package repo
#        uses: cpina/github-action-push-to-another-repository@master
#        env:
#          API_TOKEN_GITHUB:
#        with:
#          source-directory: src_install
#          destination-repository-name: hypertrace-pythonagent
#          destination-github-username: rcbj
#          target-branch: main
