on:
  push:
    branches: [main]
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**/*.md"
      - "LICENSE"

  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9"]

    steps:
      - name: Run apt-get update
        run: sudo apt-get update

      - name: Install make
        run: sudo apt-get install make

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pip
        run: sudo apt-get install python3-pip

      - uses: actions/checkout@v2

      - name: Install tox
        run: pip install --user -r dev-requirements.txt

      - name: Run pylint on this branch to generate a report
        run: make lint

      - name: Install protobuf compiler
        run: |
          sudo apt-get install -y protobuf-compiler

      - name: Run tests
        run: PYTHON_VERSION=${{ matrix.python }} make test

      - name: Build package
        run: make build
