name: Branch
on:
  push:
    branches: [main]
    paths-ignore:
      - "**/*.md"
      - "docs/*.html"
      - "LICENSE"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**/*.md"
      - "docs/*.html"
      - "LICENSE"

  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9"]

    steps:
      - name: Run apt-get update
        run: sudo apt-get update

      - name: Install Make
        run: sudo apt-get install make

      - name: Install Python
        run: |
          which python
          sudo apt install software-properties-common
          sudo add-apt-repository ppa:deadsnakes/ppa -y
          sudo apt-get install python${{ matrix.python-version }}
          sudo apt-get install python3-all
          python --version

      - name: Install pip
        run: sudo apt-get install python3-pip

      - name: Install pip build
        run: python3 -m pip install --upgrade build

      - uses: actions/checkout@v2

      - name: Install tox
        run: pip install --user -r dev-requirements.txt

      - name: Lint files
        run: make lint

      - name: Install protobuf compiler
        run: |
          sudo apt-get install -y protobuf-compiler
          protoc --version
          pip uninstall --yes protobuf python3-protobuf
          pip install --upgrade --no-input pip
          pip install --upgrade --no-input protobuf

      # while pytest-asyncio is listed in the integration tests deps, we see this missing when
      # running the test, hence we force the install.
      - name: Force install pytest-asyncio
        run: sudo pip install pytest-asyncio flask mysql-connector-python==8.0.23 psycopg2-binary==2.8.6 pytest-postgresql==3.1.1 aiohttp==3.7.4

      - name: Run tests
        run: PYTHON_VERSION=${{ matrix.python-version }} make test

      - name: Build package
        run: make build
