name: Branch
on:
  push:
    branches: [main]
    paths-ignore:
      - "**/*.md"
      - "docs/*.html"
      - "LICENSE"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**/*.md"
      - "docs/*.html"
      - "LICENSE"

  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8.9", "3.9"]

    steps:
      - name: Run apt-get update
        run: sudo apt-get update

      - name: Install Make
        run: sudo apt-get install make

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          pip install -r requirements.txt -r dev-requirements.txt

      - name: Lint files
        run: make lint

      - name: Install protobuf compiler
        run: |
          sudo apt-get install -y protobuf-compiler
          protoc --version
          pip uninstall --yes protobuf python3-protobuf
          pip install --upgrade --no-input pip
          pip install --upgrade --no-input protobuf

      - name: Run unit tests
        run: |
          cd tests/externalServices && docker-compose up -d && cd ../../
          python3 setup.py develop
          python3 -m pytest tests/hypertrace
          cd tests/externalServices && docker-compose down

      - name: Run integration tests
        run: |
          make test-integration


      - name: Build package
        run: make build
