name: Release
on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Python
        run: |
          sudo apt install software-properties-common &&
          sudo add-apt-repository ppa:deadsnakes/ppa -y &&
          sudo apt-get install python3.7
          python --version

      - name: Install pip
        run: sudo apt-get install python3-pip

      - name: Install pip build
        run: python3 -m pip install --upgrade build

      - name: Install protobuf compiler
        run: |
          sudo apt-get install -y protobuf-compiler
          protoc --version
          pip uninstall protobuf python3-protobuf
          pip install --upgrade pip
          pip install --upgrade protobuf

      - name: Build package
        run: make build

      - name: Publish a Python distribution to PyPI
        # This action relies on the package files being present in ./dist folder
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
